logging:
  path: ./logs

jalgoarena:
  api:
    url: ${JALGOARENA_API_URL:http://localhost:5001}

server:
  port: ${PORT:5006}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:26257}/jalgoarena?sslmode=disable
    username: ${COCKROACH_USERNAME:jalgo}
    password: ${COCKROACH_PASSWORD:}

  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false