logging:
  path: ./logs

jalgoarena:
  api:
    url: ${JALGOARENA_API_URL:http://localhost:5001}

server:
  port: ${PORT:5006}

spring:
  jackson:
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false